inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  EnabledByDefault: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/bundle/**/*'
    - '**/*\.spec'

################################################################################
#
# Rules that depart from rubocop defaults
#
################################################################################

# RSpec/FilePath: { CustomTransform: { Magick: rmagick } }
# we may not need this after finishing RSpec conversion
# seems like `rubocop-rspec` already excludes the `spec/` directory
Style/MethodCalledOnDoEndBlock: { Exclude: [test/**/*.rb, spec/**/*.rb] }

################################################################################
#
# Rules we don't want to enable
#
################################################################################

RSpec/AlignLeftLetBrace: { Enabled: false }
RSpec/AlignRightLetBrace: { Enabled: false }
