language: ruby
env:
  - IMAGEMAGICK_VERSION=6.8.9-6
install:
  - sudo dpkg --purge imagemagick
  - sudo apt-get install build-essential libx11-dev libxext-dev zlib1g-dev libpng12-dev libjpeg-dev libfreetype6-dev libxml2-dev
  - sudo apt-get build-dep imagemagick
  - wget http://www.imagemagick.org/download/ImageMagick-${IMAGEMAGICK_VERSION}.tar.gz
  - tar -xzvf ImageMagick-${IMAGEMAGICK_VERSION}.tar.gz
  - cd ImageMagick-${IMAGEMAGICK_VERSION}
  - ./configure --with-prefix=/usr
  - sudo make install
  - cd ..
rvm:
  - 1.9
  - 2.0
  - 2.1
